enum actionTypeKeys {
	GET_PHOTOS = "GET_PHOTOS",
	GET_PHOTO_SUCCESS = "GET_PHOTO_SUCCESS",
	GET_PHOTO_FAIL = "GET_PHOTO_FAIL",
	GET_PHOTO_DETAIL = "GET_PHOTO_DETAIL",
	GET_PHOTO_DETAIL_SUCCESS = "GET_PHOTO_DETAIL_SUCCESS",
	GET_PHOTO_DETAIL_FAIL = "GET_PHOTO_DETAIL_FAIL",
	TOGGLE_FAVORITE_PHOTO = "TOGGLE_FAVORITE_PHOTO",
	SEARCH_PHOTO = "SEARCH_PHOTO",
	SEARCH_PHOTO_SUCCESS = "SEARCH_PHOTO_SUCCESS",
}

export default actionTypeKeys;
